import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/login.module.css'
import { BsArrowDown, BsArrowUp, BsFillBellFill,BsFillCartFill, BsMenuDown, BsSearch, BsSortDown } from "react-icons/bs";
import { useState } from 'react';
import HeaderPage from '../header';


const LoginPage = () => {
    return(
        <div className={styles.conatiner}>
            <Head key={1}>
              <title>Login Next App</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
            </Head>
            <header className={styles.header}>
                <img className={styles.img} src='/vercel.svg'/>
            </header>
            <div className={styles.main}>
                <div className={styles.card_main}>
                    <p>Login</p>
                </div>
            </div>
        </div>

    )
}

export default LoginPage