import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'
import HeaderPage from './header'
import Card_page from './product/card'

const img_content = ["/img-cth1.jpg","/img-cth2.jpg","/img-cth3.jpg"]
// database
import firestore from "../firebase/clientApp";
import {collection,QueryDocumentSnapshot,DocumentData,query,where,limit,getDocs, updateDoc, doc, deleteDoc} from "@firebase/firestore";

const ProductCollection = collection(firestore,"product_table");

export default function Home() {
  const [img_conten, setimg_conten] = useState({})
  const [on_categori, seton_categori] = useState(1)
  const [data_product, setdata_product] = useState([])
  useEffect(()=>{
    content_slide(0)
    getData()
  },[])

  const getData = async () => {
    const base_product = []
     const Query = query(ProductCollection);
     const querySnapshot = await getDocs(Query); 
     querySnapshot.forEach((snapshot) => {
         var a = snapshot
          base_product.push(a)
     });
     setdata_product(base_product)
  };

  const content_slide = (a) => {
    setimg_conten({img:img_content[a], value:parseInt(a)+1})
    setTimeout(()=>{
      if(a === 2){
        content_slide(0)
      }else{
        content_slide(a+1)
      }
    },60000)
  }

  return (
    <div className={styles.container}>
      <Head key={1}>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeaderPage/>
      <div style={{backgroundImage: `url(${img_conten.img})`}} className={styles.content}>
        <div className={styles.content_absolute}>
          <p className={styles.content_text}>{img_conten.value} / {img_content.length}</p>
        </div>
      </div>
      <div className={styles.main}>
        <div className={styles.main_header2}>
          {[1,2,3,4,5].map((a,b)=>{
            return b === 0 ? (
              <button onClick={()=>seton_categori(a)} style={a === on_categori ? {backgroundColor:"white"}:null} className={styles.card_main_header3}>
                Makanan
              </button>
            ):(
              <button onClick={()=>seton_categori(a)} style={a === on_categori ? {backgroundColor:"white"}:null} className={styles.card_main_header3}>
                masakan
              </button>
            )
          })}
        </div>
        {/* /////////////////////////// */}
        <div className={styles.main_header}>
          {[1,2,3,4,5].map((a,b)=>{
            return b === 0 ? (
              <button onClick={()=>seton_categori(a)} style={a === on_categori ? {backgroundColor:"white"}:null} className={styles.card_main_header1}>
                Makanan
              </button>
            ):(
              <button onClick={()=>seton_categori(a)} style={a === on_categori ? {backgroundColor:"white"}:null} className={styles.card_main_header}>
                masakan
              </button>
            )
          })}
        </div>
        <div className={styles.main_main}>
          {data_product.map(a=>{
            return <Card_page res={a}/>
          })}
        </div>
      </div>
    </div>
  )
}

