import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'
import HeaderPage from './header'
import Card_page from "./product/index"

const img_content = ["/img-cth1.jpg","/img-cth2.jpg","/img-cth3.jpg"]
// database
import firestore from "../firebase/clientApp";
import {collection,QueryDocumentSnapshot,DocumentData,query,where,limit,getDocs, updateDoc, doc, deleteDoc} from "@firebase/firestore";
import { Router, useRouter } from 'next/router'
import PageNull from './page_null'

const ProductCollection = collection(firestore,"product_table");

export default function Home() {
  const [img_conten, setimg_conten] = useState(0)
  const [on_categori, seton_categori] = useState(1)
  const [data_product, setdata_product] = useState([])
  const router = useRouter()

  useEffect(()=>{
    getData()
  },[])

  const getData = async () => {
    const base_product = []
     const Query = query(ProductCollection);
     const querySnapshot = await getDocs(Query); 
     querySnapshot.forEach((snapshot) => {
         var a = snapshot
          base_product.push(a)
     });
     if(base_product.length !== 0){
       setdata_product(base_product)
     }
  };

  const content_slide = (a) => {
    return(
      <div key={1} style={{backgroundImage: `url(${img_content[img_conten]})`}} className={styles.content}>
        <div className={styles.content_absolute}>
          <p className={styles.content_text}>{parseInt(img_conten)+1} / {img_content.length}</p>
        </div>
      </div>
    )
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeaderPage/>
      {content_slide()}
      <div className={styles.main}>
        <div className={styles.main_header2}>
          {[1,2,3,4,5].map((a,b)=>{
            return b === 0 ? (
              <button onClick={()=>seton_categori(a)} style={a === on_categori ? {backgroundColor:"white"}:null} className={styles.card_main_header3}>
                Makanan
              </button>
            ):(
              <button onClick={()=>seton_categori(a)} style={a === on_categori ? {backgroundColor:"white"}:null} className={styles.card_main_header3}>
                masakan
              </button>
            )
          })}
        </div>
        {/* /////////////////////////// */}
        <div className={styles.main_header}>
          {[1,2,3,4,5].map((a,b)=>{
            return b === 0 ? (
              <button onClick={()=>seton_categori(a)} style={a === on_categori ? {backgroundColor:"white"}:null} className={styles.card_main_header1}>
                Makanan
              </button>
            ):(
              <button onClick={()=>seton_categori(a)} style={a === on_categori ? {backgroundColor:"white"}:null} className={styles.card_main_header}>
                masakan
              </button>
            )
          })}
        </div>
        {data_product.length === 0 ? (
          <div className={styles.card_null}><PageNull message={"Item Product Tidak ada"}/></div>
        ):(
        <div className={styles.main_main}>
          {data_product.map((a,b)=>{
            return <Card_page key={a.id} onPress={()=>router.push({pathname:"/product/show", query:{ref_id:a.id, ref_query:a.data()}})} data={a}/>
          })}
        </div>
        )}
      </div>
    </div>
  )
}

